### PR TITLE
fix: Klondike tutorial to use built-in `world` and `camera`

### LINKED ISSUE #2798: Klondike Tutorial step4.md does not keep all 52 card under KlondikeGame ownership
# Current bug behavior
During the shuffle and deal in Step 4 of Flame's Klondike Tutorial, 26 Card objects are removed from KlondikeGame ownership and placed under Tableau pile ownership. This contradicts what the documentation says earlier: "the `Card` components are owned directly by the `KlondikeGame` itself, whereas the `StockPile` and other piles are merely aware of which cards are currently placed there". This is true of the StockPile immediately after the deal when it has 24 cards in it and the List of Cards in KlondikeGame has the same 24 cards. But it is not true of the other piles - they are holding 26 cards which have been removed from the master-list in KlondikeGame. I believe the problem lies in the use of cards.removeLast() when dealing the cards, both in the `step4.md` file and in the `app/lib/step4/klondike_game.dart` file. Same bug in 2 places.

# Expected behavior
The List\<Card\>cards should contain 52 cards at all times after the shuffle() operation.

In the Klondike Tutorial app code as it stands, nothing is visibly wrong on the screen, but the problem will appear when you try to add features at the Klondike Game level that involve all 52 cards, such as making them fly off the screen when the user wins. I discovered the problem when trying to implement such a feature.

# Steps to reproduce
Add a print() statement to a running version of the Klondike game, to print out the number of cards in List\<Card\> in `app/lib/step4/klondike_game.dart`, immediately after the deal. It should be 52 but will be 24 with the code as it stands.

# Flutter doctor output
```
[✓] Flutter (Channel stable, 3.13.6, on macOS 12.6 21G115 darwin-arm64, locale
    en-AU)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[!] Android Studio (not installed)
[✓] VS Code (version 1.82.2)
[✓] Connected device (1 available)
[✓] Network resources
```
# More information
I have a solution to the problem and am interested in working on a PR for it.

### PR DESCRIPTION
**Pull request by IanWadham**
# Description
Firstly, (re Issue #2799) Flame 1.9.x broke the Klondike Tutorial, which was not set up to use the new built-in `world` and `camera`. So I modified the `KlondikeGame`'s `onLoad()` code to use the built-in `world` and `camera` and no longer create its own `World` and `CameraComponent`. I also updated the `step2.md` documentation file, which instructs new users of Flame on how to use the `world` and the `camera`, how to set up a game-oriented co-ordinate system and how to fit it into the device screen.

Secondly, (re Issue #2798) Klondike was not adhering to the design stated in the Tutorial, that all 52 `Card` objects would be owned by the `KlondikeGame`. During the shuffle and deal sequence it was using `removeLast()` on the `List\<Card\>cards`, where the cards are kept, the result being that only 24 of the 52 cards were left in the list after the deal. I have fixed the bug and updated the Tutorial documentation (`step4`) which discusses how the deal is coded. 

This bug does not affect the gameplay as it stands, but it does block the way to future features at the game level, such as an option to re-deal or a win-animation where all cards fly off the screen.

## Checklist
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [-] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?
- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues
Closes #2798 and #2799. But I think there may be preliminary versions of the KlondikeGame code in the `step2/` and `step3/` directory structures that need fixing for Issue #2799 and maybe the snippets that copy the code and make it run, during the Tutorial, will also need adjusting.

### CODE REVIEW

File: doc/tutorials/klondike/app/.gitignore [hunk 1]
```diff
@@ -0,0 +1,44 @@
+# Miscellaneous
```
Comment (spydon) [inline doc/tutorials/klondike/app/.gitignore:1]: .gitignore files should not be included, we already have a root gitignore

File: doc/tutorials/klondike/app/.metadata [hunk 2]
```diff
@@ -0,0 +1,42 @@
+# This file tracks properties of this Flutter project.
```
Comment (spydon) [inline doc/tutorials/klondike/app/.metadata:1]: This file should not be added since this is not an app that is being released, but just an example.

File: doc/tutorials/klondike/app/README.md [hunk 3]
```diff
@@ -0,0 +1,16 @@
+# app
```
Comment (spydon) [inline doc/tutorials/klondike/app/README.md:1]: This is the default readme, either modify it to explain the example, or remove it.

File: doc/tutorials/klondike/app/lib/main.dart [hunk 4]
```diff
@@ -1,11 +1,12 @@
-import 'dart:html'; // ignore: avoid_web_libraries_in_flutter
+// import 'dart:html'; // ignore: avoid_web_libraries_in_flutter
```
Comment (spydon) [inline doc/tutorials/klondike/app/lib/main.dart:1]: This should not be commented out, since this tutorial runs in the browser.

File: doc/tutorials/klondike/app/lib/step4/klondike_game_11101345.dart [hunk 5]
```diff
@@ -0,0 +1,87 @@
+import 'dart:ui';
```
Comment (spydon) [inline doc/tutorials/klondike/app/lib/step4/klondike_game_11101345.dart:1]: What is this file?

File: doc/tutorials/klondike/app/lib/step4/my_klondike_game.dart [hunk 6]
```diff
@@ -0,0 +1,91 @@
+import 'dart:ui';
```
Comment (spydon) [inline doc/tutorials/klondike/app/lib/step4/my_klondike_game.dart:1]: What is this file?

File: doc/tutorials/klondike/app/.gitignore (hunk 1 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/.gitignore:1]: I don't know how this file and the files you refer to in subsequent comments became visible here. They are in my work-area on my local repo and laptop computer, but I certainly never committed them. I'll investigate tomorrow,

Comment (IanWadham) [reply doc/tutorials/klondike/app/.gitignore:1]: This commit is the culprit. I was using the GitHub Desktop app (for MacOS) to push my own local commits to remote. Unfortunately I filled in some fields and pushed a button that somehow bundled up unwanted files, added them, committed them and pushed them. Most of the files were generated by Flutter's create. A couple were my own scratch-files. My git skills are rusty and were never great, so I do not know how to erase this commit and all the spurious files from my forked Flame repo on GitHub and also my local repository. Can you help, Spydon?

commit 18f71bece67fad79b71b9185dc18101f81f0df27 (HEAD -> fix#2798)
Author: IanWadham <iandw.au@gmail.com>
Date:   Wed Oct 11 19:57:53 2023 +1100

    Fixes for issue #2798
    
    The klondike_game.dart code was not keeping all 52 playing cards under its control, as required by the design. The code and doco also had to be fixed because it was broken by world and camera changes in Flame 1.9.x.

File: doc/tutorials/klondike/app/lib/main.dart [hunk 7]
```diff
@@ -1,11 +1,12 @@
...
 import 'package:flutter/widgets.dart';
 import 'step2/main.dart' as step2;
 import 'step3/main.dart' as step3;
 import 'step4/main.dart' as step4;
 
 void main() {
-  var page = window.location.search ?? '';
+  // var page = window.location.search ?? '';
+  var page = 'step4';
```
Comment (domesticmouse) [inline doc/tutorials/klondike/app/lib/main.dart:9]: This change should probably also be reverted

File: doc/tutorials/klondike/app/lib/step4/klondike_game.dart [hunk 8]
```diff
@@ -45,19 +45,15 @@ class KlondikeGame extends FlameGame {
       ),
     );
 
-    final world = World()
-      ..add(stock)
-      ..add(waste)
-      ..addAll(foundations)
-      ..addAll(piles);
-    add(world);
+    world.add(stock);
```
Comment (domesticmouse) [inline doc/tutorials/klondike/app/lib/step4/klondike_game.dart:48]: I'm curious why the replacement of cascade `add`s with individual `add`s. Also, in the transformation, you lost adding `world` to the current game component.

File: doc/tutorials/klondike/app/lib/step4/klondike_game.dart [hunk 9]
```diff
@@ -45,19 +45,15 @@ class KlondikeGame extends FlameGame {
...
+    world.addAll(foundations);
+    world.addAll(piles);
 
-    final camera = CameraComponent(world: world)
-      ..viewfinder.visibleGameSize =
-          Vector2(cardWidth * 7 + cardGap * 8, 4 * cardHeight + 3 * cardGap)
-      ..viewfinder.position = Vector2(cardWidth * 3.5 + cardGap * 4, 0)
-      ..viewfinder.anchor = Anchor.topCenter;
-    add(camera);
+    camera.viewfinder.visibleGameSize =
```
Comment (domesticmouse) [inline doc/tutorials/klondike/app/lib/step4/klondike_game.dart:53]: I'm still curious about why the elimination of the cascade operator. It shouldn't change anything here.

File: doc/tutorials/klondike/app/lib/main.dart (hunk 7 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/main.dart:9]: It was accidentally committed and pushed. I have written to Spydon above re how to get the offending commit expunged from both repositories (my local and remote) and its history deleted. The changes are just my hacks to avoid compilation errors on Apple MacOS and get the Klondike app to run.

File: doc/tutorials/klondike/app/lib/step4/klondike_game.dart (hunk 8 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/step4/klondike_game.dart:48]: That change is to comply with Flame 1.9.x, where `world` and `camera` objects are pre-built into FlameGame and you don't need to do anything with `world` other than add components to it IIUC. Re cascade syntax, this Tutorial is aimed at programmers who are new to Flame and perhaps also to Dart, so I think more explicit syntax, which is also used in other OO languages is the way to go.

File: doc/tutorials/klondike/app/lib/step4/klondike_game.dart (hunk 9 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/step4/klondike_game.dart:53]: As before, `camera` is now an built-in object in FlameGame and is inherited. And the Tutorial text is discussing how to define a game's co-ordinate system to suit the objects in the game (i.e. cards)i and why we anchor the camera at top center. So I think more explicit syntax helps to emphasise the key points, which are the parameters used to lay out the game and set up the camera.

File: doc/tutorials/klondike/app/.metadata (hunk 2 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/.metadata:1]: Flutter-generated file. We need to eradicate commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 which unintentionally added and commited it.

File: doc/tutorials/klondike/app/README.md (hunk 3 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/README.md:1]: Flutter-generated file. We need to eradicate commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 which unintentionally added and committed it.

File: doc/tutorials/klondike/app/test/widget_test.dart [hunk 10]
```diff
@@ -0,0 +1,30 @@
+// This is a basic Flutter widget test.
```
[the remark this answers is not in the document]
Comment (IanWadham) [reply doc/tutorials/klondike/app/test/widget_test.dart:1]: Flutter-generated directory and file. We need to eradicate commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 which unintentionally added and committed it.

File: doc/tutorials/klondike/app/.gitignore (hunk 1 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/.gitignore:1]: This .gitignore is a Flutter-generated file. We need to eradicate commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 which unintentionally added and committed it.

File: doc/tutorials/klondike/app/lib/main.dart (hunk 4 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/main.dart:1]: This is just a hack I used to get this `main.dart` to run on Apple MacOS without compilation errors and a crash. We need to eradicate commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 which unintentionally added and committed this file.

File: doc/tutorials/klondike/app/lib/step4/klondike_game_11101345.dart (hunk 5 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/step4/klondike_game_11101345.dart:1]: It's a scratch-file I used to help sort out chunks of changes and commits. We need to eradicate commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 which unintentionally added and committed it.

File: doc/tutorials/klondike/app/lib/step4/my_klondike_game.dart (hunk 6 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/step4/my_klondike_game.dart:1]: It's a scratch-file I used to help sort out chunks of changes and commits. We need to eradicate commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 which unintentionally added and committed it.

File: doc/tutorials/klondike/app/lib/step4/klondike_game.dart (hunk 8 above)
Comment (domesticmouse) [reply doc/tutorials/klondike/app/lib/step4/klondike_game.dart:48]: Ahhh, this makes sense. Thanks for the explanation!

File: doc/tutorials/klondike/app/.gitignore (hunk 1 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/.gitignore]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

File: doc/tutorials/klondike/app/.metadata (hunk 2 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/.metadata]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

File: doc/tutorials/klondike/app/README.md (hunk 3 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/README.md]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

File: doc/tutorials/klondike/app/lib/main.dart (hunk 4 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/main.dart]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

File: doc/tutorials/klondike/app/lib/step4/klondike_game_11101345.dart (hunk 5 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/step4/klondike_game_11101345.dart]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

File: doc/tutorials/klondike/app/lib/step4/my_klondike_game.dart (hunk 6 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/step4/my_klondike_game.dart]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

File: doc/tutorials/klondike/app/test/widget_test.dart (hunk 10 above)
[the remark this answers is not in the document]
Comment (IanWadham) [reply doc/tutorials/klondike/app/test/widget_test.dart]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

File: doc/tutorials/klondike/app/lib/main.dart (hunk 7 above)
Comment (IanWadham) [reply doc/tutorials/klondike/app/lib/main.dart]: The offending commit https://github.com/flame-engine/flame/commit/18f71bece67fad79b71b9185dc18101f81f0df27 has been reverted.

**Comment by IanWadham** [comment]
This PR is ready to continue its review now, AFAIK. Please review.

**Review by spydon — APPROVED** [review]
